<?php

namespace Database\Seeders;

use App\Models\Region;
use App\Models\Ruta;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class RutaSeeder extends Seeder
{
    public function run(): void
    {
        $usuarios = User::pluck('id')->all();
        $regionPorSlug = Region::pluck('id', 'slug');

        foreach ($this->rutasReales() as $datos) {
            $datos['user_id'] = fake()->randomElement($usuarios);
            $datos['region_id'] = $regionPorSlug[$datos['region_slug']];
            unset($datos['region_slug']);
            $datos['slug'] = Str::slug($datos['titulo']);
            $datos['imagen_path'] = $this->copiarImagen($datos['slug']);

            Ruta::updateOrCreate(['slug' => $datos['slug']], $datos);
        }
    }

    private function copiarImagen(string $slug): ?string
    {
        $origen = database_path("seeders/images/rutas/{$slug}.jpg");

        if (! file_exists($origen)) {
            return null;
        }

        $destino = "rutas/{$slug}.jpg";
        Storage::disk('public')->put($destino, file_get_contents($origen));

        return $destino;
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function rutasReales(): array
    {
        return [
            [
                'titulo' => 'Senda del Cares',
                'region_slug' => 'asturias',
                'descripcion' => 'Espectacular ruta por la garganta del río Cares en los Picos de Europa, considerada la garganta divina.',
                'descripcion_larga' => "La Senda del Cares discurre por una garganta tallada por el río Cares entre Caín (León) y Poncebos (Asturias), con un paisaje impresionante de paredes verticales, túneles excavados en la roca y pasarelas colgantes.\n\nEs una de las rutas más conocidas y transitadas de los Picos de Europa, accesible para cualquier persona en buena forma física aunque sin grandes desniveles. La mejor época para hacerla es primavera y otoño, evitando los meses centrales del verano por la afluencia.",
                'categoria' => 'naturaleza',
                'dificultad' => 'moderada',
                'distancia_km' => 12.0,
                'duracion_min' => 240,
                'lat_inicio' => 43.221,
                'lng_inicio' => -4.892,
                'punto_inicio' => 'Caín de Valdeón',
                'punto_fin' => 'Poncebos',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => true,
            ],
            [
                'titulo' => 'Caminito del Rey',
                'region_slug' => 'andalucia',
                'descripcion' => 'Pasarela colgante reabierta al público en el desfiladero de los Gaitanes, en Málaga.',
                'descripcion_larga' => "El Caminito del Rey serpentea por las paredes verticales del desfiladero de los Gaitanes, a más de 100 metros sobre el río Guadalhorce. Tras décadas de abandono, fue rehabilitado en 2015 y hoy es uno de los recorridos más espectaculares de España.\n\nEl recorrido lineal de poco más de 7 kilómetros se completa en unas tres horas, e incluye pasarelas de madera ancladas a la pared, un puente colgante y vistas inolvidables del paisaje malagueño. Las entradas se compran con antelación y se acceden con horario fijo.",
                'categoria' => 'naturaleza',
                'dificultad' => 'facil',
                'distancia_km' => 7.7,
                'duracion_min' => 210,
                'lat_inicio' => 36.9293,
                'lng_inicio' => -4.7796,
                'punto_inicio' => 'Ardales',
                'punto_fin' => 'El Chorro',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => true,
            ],
            [
                'titulo' => 'Camino de Santiago Francés (etapa final)',
                'region_slug' => 'galicia',
                'descripcion' => 'Los últimos 100 km del Camino Francés, desde Sarria hasta Santiago de Compostela.',
                'descripcion_larga' => "Los últimos 100 kilómetros del Camino Francés, desde Sarria hasta Santiago, son la opción más popular para obtener la Compostela. La ruta atraviesa pueblos rurales gallegos, bosques de robles y castaños, y cruza ríos por puentes medievales.\n\nEs un recorrido accesible para personas con poca experiencia en senderismo, dividido en cinco etapas de unos 20 kilómetros cada una. La llegada a la Plaza del Obradoiro, frente a la catedral, es el momento culminante del viaje para miles de peregrinos cada año.",
                'categoria' => 'cultura',
                'dificultad' => 'moderada',
                'distancia_km' => 115.0,
                'duracion_min' => 1800,
                'lat_inicio' => 42.7795,
                'lng_inicio' => -7.4129,
                'punto_inicio' => 'Sarria',
                'punto_fin' => 'Santiago de Compostela',
                'mejor_epoca' => 'primavera y verano',
                'destacada' => true,
            ],
            [
                'titulo' => 'Ruta del Vino de la Rioja',
                'region_slug' => 'la-rioja',
                'descripcion' => 'Recorrido entre viñedos y bodegas centenarias por los pueblos riojanos más emblemáticos.',
                'descripcion_larga' => "La Ruta del Vino de la Rioja atraviesa los principales municipios productores de la Rioja Alta y Alavesa, con paradas en bodegas históricas, catas y enoturismo de primer nivel.\n\nIncluye visitas a Haro, Briones, San Vicente de la Sonsierra y Laguardia, además de paseos entre viñedos antiguos y catas guiadas. Es una ruta enogastronómica más que un sendero, ideal para hacerla en coche o en bici durante varios días.",
                'categoria' => 'gastronomia',
                'dificultad' => 'facil',
                'distancia_km' => 60.0,
                'duracion_min' => 720,
                'lat_inicio' => 42.5774,
                'lng_inicio' => -2.8467,
                'punto_inicio' => 'Haro',
                'punto_fin' => 'Logroño',
                'mejor_epoca' => 'septiembre y octubre',
                'destacada' => true,
            ],
            [
                'titulo' => 'Sendero de los Lagos de Covadonga',
                'region_slug' => 'asturias',
                'descripcion' => 'Ruta circular por los lagos Enol y Ercina en el corazón de los Picos de Europa.',
                'descripcion_larga' => "El sendero circular alrededor de los lagos Enol y Ercina, en el Parque Nacional de los Picos de Europa, ofrece algunas de las vistas más fotografiadas de Asturias.\n\nLa ruta combina pradería de alta montaña, ganado autóctono pastando libre y panorámicas de los Picos. Es accesible para cualquier nivel de senderismo y muy popular en verano. En temporada alta el acceso en coche está restringido y hay que llegar en autobús lanzadera desde Cangas de Onís.",
                'categoria' => 'naturaleza',
                'dificultad' => 'facil',
                'distancia_km' => 5.5,
                'duracion_min' => 120,
                'lat_inicio' => 43.2746,
                'lng_inicio' => -4.9831,
                'punto_inicio' => 'Lago Enol',
                'punto_fin' => 'Lago Enol',
                'mejor_epoca' => 'verano y principios de otoño',
                'destacada' => true,
            ],
            [
                'titulo' => 'Cabo de Gata: Ruta de Las Negras a San José',
                'region_slug' => 'andalucia',
                'descripcion' => 'Sendero costero por calas vírgenes y acantilados volcánicos del parque natural más árido de Europa.',
                'descripcion_larga' => "El sendero costero del Cabo de Gata recorre el tramo entre Las Negras y San José, atravesando algunas de las calas más espectaculares del Mediterráneo: Cala San Pedro, Cala del Plomo y la imponente playa de Mónsul.\n\nEs un parque natural protegido con una geología volcánica única en Europa. La ruta requiere llevar agua suficiente porque no hay fuentes en el camino y el sol pega fuerte casi todo el año. Recomendable hacerla en primavera u otoño.",
                'categoria' => 'naturaleza',
                'dificultad' => 'moderada',
                'distancia_km' => 18.5,
                'duracion_min' => 360,
                'lat_inicio' => 36.8761,
                'lng_inicio' => -2.0117,
                'punto_inicio' => 'Las Negras',
                'punto_fin' => 'San José',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => false,
            ],
            [
                'titulo' => 'Sierra de Tramuntana: Es Cornadors',
                'region_slug' => 'baleares',
                'descripcion' => 'Ascensión a un mirador natural sobre el valle de Sóller en plena Tramuntana mallorquina.',
                'descripcion_larga' => "La ruta a Es Cornadors parte de Sóller y asciende por un sendero histórico de carboneros hasta uno de los miradores más espectaculares de la sierra de Tramuntana, con vistas sobre el valle, el mar y los acantilados de la costa norte.\n\nLa subida tiene un desnivel considerable pero ningún tramo técnico. La sierra es Patrimonio de la Humanidad por la UNESCO y combina naturaleza, agricultura tradicional y arquitectura rural mallorquina.",
                'categoria' => 'naturaleza',
                'dificultad' => 'exigente',
                'distancia_km' => 14.0,
                'duracion_min' => 360,
                'lat_inicio' => 39.7659,
                'lng_inicio' => 2.7148,
                'punto_inicio' => 'Sóller',
                'punto_fin' => 'Sóller',
                'mejor_epoca' => 'invierno y primavera',
                'destacada' => false,
            ],
            [
                'titulo' => 'Vía Verde de la Sierra',
                'region_slug' => 'andalucia',
                'descripcion' => 'Antiguo trazado ferroviario reconvertido en sendero de 36 km entre Olvera y Puerto Serrano.',
                'descripcion_larga' => "Una de las vías verdes más bellas de España, sobre el antiguo trazado del ferrocarril Jerez-Almargen, nunca terminado de construir. Atraviesa 30 túneles y 4 viaductos por la sierra gaditana, con observatorios de aves y áreas recreativas.\n\nEs una ruta plana ideal para hacer en bicicleta, accesible para familias y completamente señalizada. La estación de Olvera reconvertida en alojamiento es un buen punto de partida o final.",
                'categoria' => 'naturaleza',
                'dificultad' => 'facil',
                'distancia_km' => 36.0,
                'duracion_min' => 360,
                'lat_inicio' => 36.937,
                'lng_inicio' => -5.262,
                'punto_inicio' => 'Olvera',
                'punto_fin' => 'Puerto Serrano',
                'mejor_epoca' => 'todo el año',
                'destacada' => false,
            ],
            [
                'titulo' => 'Hoces del Río Lobos',
                'region_slug' => 'castilla-y-leon',
                'descripcion' => 'Cañón fluvial entre Soria y Burgos con la ermita templaria de San Bartolomé.',
                'descripcion_larga' => "El cañón del Río Lobos es un parque natural de paredes calizas, buitreras y cuevas que ha inspirado a poetas como Antonio Machado. La ruta lineal hasta la ermita templaria de San Bartolomé, en pleno cañón, es la opción más popular.\n\nLa ermita del siglo XIII destaca por sus simbología templaria y su localización casi mágica entre los acantilados. La ruta es prácticamente plana y discurre por una pista forestal cómoda.",
                'categoria' => 'patrimonio',
                'dificultad' => 'facil',
                'distancia_km' => 6.5,
                'duracion_min' => 150,
                'lat_inicio' => 41.7544,
                'lng_inicio' => -3.0581,
                'punto_inicio' => 'Ucero',
                'punto_fin' => 'Ermita de San Bartolomé',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => false,
            ],
            [
                'titulo' => 'Camí de Cavalls (etapa Es Grau - Favàritx)',
                'region_slug' => 'baleares',
                'descripcion' => 'Etapa costera del antiguo camino circular de Menorca, con tramos vírgenes y faro emblemático.',
                'descripcion_larga' => "Una de las etapas más bellas del Camí de Cavalls, el antiguo sendero defensivo que rodea Menorca. Discurre entre el Parque Natural de s'Albufera des Grau y el faro de Favàritx, con cambios bruscos de paisaje y calas escondidas.\n\nEl tramo combina caminos de tierra rojiza, dunas, lagunas costeras y la geología negra del Cap de Favàritx, uno de los puntos más fotografiados de la isla. Es accesible aunque expuesto al viento y al sol.",
                'categoria' => 'naturaleza',
                'dificultad' => 'moderada',
                'distancia_km' => 10.0,
                'duracion_min' => 180,
                'lat_inicio' => 39.9508,
                'lng_inicio' => 4.2628,
                'punto_inicio' => 'Es Grau',
                'punto_fin' => 'Faro de Favàritx',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => false,
            ],
            [
                'titulo' => 'Camino de Santiago Portugués (etapa final)',
                'region_slug' => 'galicia',
                'descripcion' => 'Última etapa del camino que cruza desde Tui hasta Santiago de Compostela por la Galicia interior.',
                'descripcion_larga' => "El Camino Portugués es el segundo más popular después del Francés, cruza desde Portugal hasta Santiago por la Galicia más rural. La etapa desde Tui, en la frontera, hasta Santiago supone unos 115 kilómetros divididos en cinco jornadas tranquilas.\n\nAtraviesa pueblos gallegos como Pontevedra, Caldas de Reis y Padrón, con buenos albergues, gastronomía marinera y un paisaje suave de robledales y río Ulla. Es ideal para peregrinos primerizos que buscan un camino menos masificado.",
                'categoria' => 'cultura',
                'dificultad' => 'moderada',
                'distancia_km' => 115.0,
                'duracion_min' => 1800,
                'lat_inicio' => 42.0454,
                'lng_inicio' => -8.6418,
                'punto_inicio' => 'Tui',
                'punto_fin' => 'Santiago de Compostela',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => true,
            ],
            [
                'titulo' => 'Ruta del Quijote: Campo de Criptana',
                'region_slug' => 'castilla-la-mancha',
                'descripcion' => 'Recorrido literario por los molinos de viento que inspiraron a Cervantes en el corazón de La Mancha.',
                'descripcion_larga' => "Una ruta cervantina que recorre los emblemáticos molinos de viento de Campo de Criptana, los gigantes contra los que se enfrentó Don Quijote. La ruta sale del cerro de la Paz y desciende por el casco antiguo hasta el conjunto de molinos restaurados.\n\nEs un paseo familiar por uno de los paisajes más reconocibles de España, con interpretación libre de los pasajes cervantinos en los molinos visitables. Desde lo alto, la planicie manchega ofrece atardeceres memorables, especialmente en otoño.",
                'categoria' => 'cultura',
                'dificultad' => 'facil',
                'distancia_km' => 4.5,
                'duracion_min' => 90,
                'lat_inicio' => 39.4042,
                'lng_inicio' => -3.1247,
                'punto_inicio' => 'Campo de Criptana',
                'punto_fin' => 'Cerro de la Paz',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => false,
            ],
            [
                'titulo' => 'Ruta de los Pueblos Blancos',
                'region_slug' => 'andalucia',
                'descripcion' => 'Recorrido por los pueblos blancos de la sierra de Cádiz: Arcos, Grazalema, Setenil y Ronda.',
                'descripcion_larga' => "La ruta enlaza algunos de los pueblos más pintorescos de Andalucía, todos encalados de blanco siguiendo la tradición árabe. Arcos de la Frontera abre el camino sobre un peñón espectacular, Grazalema sorprende por su pluviometría récord en el corazón de la sierra, y Setenil de las Bodegas se mete bajo la roca con casas-cueva imposibles.\n\nEs una ruta para hacer en coche durante varios días, con multitud de paradas para senderos cortos, gastronomía serrana y observación de aves rapaces. Ronda, ya en Málaga, suele cerrar el recorrido como el pueblo blanco más célebre.",
                'categoria' => 'cultura',
                'dificultad' => 'facil',
                'distancia_km' => 130.0,
                'duracion_min' => 1440,
                'lat_inicio' => 36.7515,
                'lng_inicio' => -5.8011,
                'punto_inicio' => 'Arcos de la Frontera',
                'punto_fin' => 'Ronda',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => true,
            ],
            [
                'titulo' => 'Camino del Cid: tramo de Burgos',
                'region_slug' => 'castilla-y-leon',
                'descripcion' => 'Sigue las huellas del Cid Campeador desde Vivar a Burgos por el valle del Ubierna.',
                'descripcion_larga' => "El Camino del Cid es la ruta turística que sigue las andanzas del Cantar de mio Cid desde Burgos hasta Valencia. Este primer tramo enlaza Vivar del Cid, lugar de nacimiento del héroe, con la ciudad de Burgos por una pista forestal sin grandes desniveles.\n\nEl recorrido cruza el valle del Ubierna entre campos de cereal y enebrales, con paneles informativos sobre los pasajes del Cantar. Termina en la propia ciudad de Burgos, junto a la catedral, donde reposan los restos del Cid y su esposa Jimena.",
                'categoria' => 'cultura',
                'dificultad' => 'moderada',
                'distancia_km' => 18.0,
                'duracion_min' => 300,
                'lat_inicio' => 42.4310,
                'lng_inicio' => -3.6837,
                'punto_inicio' => 'Vivar del Cid',
                'punto_fin' => 'Burgos',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => false,
            ],
            [
                'titulo' => 'Ciudades Patrimonio: Salamanca, Ávila y Segovia',
                'region_slug' => 'castilla-y-leon',
                'descripcion' => 'Itinerario por tres joyas patrimoniales castellanas: Salamanca, Ávila y Segovia.',
                'descripcion_larga' => "Tres ciudades declaradas Patrimonio de la Humanidad por la UNESCO unidas en una sola ruta. Salamanca abre el recorrido con su universidad medieval y la Plaza Mayor barroca, una de las más bellas de España. Ávila ofrece la muralla mejor conservada de Europa, con sus 88 torreones y nueve puertas.\n\nSegovia cierra la ruta con dos iconos imprescindibles: el Acueducto romano del siglo I y el Alcázar que inspiró castillos de cuento. La ruta funciona en coche o en tren durante un fin de semana largo, con tres noches en cada ciudad.",
                'categoria' => 'cultura',
                'dificultad' => 'facil',
                'distancia_km' => 220.0,
                'duracion_min' => 2160,
                'lat_inicio' => 40.9701,
                'lng_inicio' => -5.6635,
                'punto_inicio' => 'Salamanca',
                'punto_fin' => 'Segovia',
                'mejor_epoca' => 'todo el año',
                'destacada' => true,
            ],
            [
                'titulo' => 'Pinchos por la Parte Vieja de San Sebastián',
                'region_slug' => 'pais-vasco',
                'descripcion' => 'Recorrido tapeo por los bares emblemáticos del casco viejo donostiarra y sus pinchos legendarios.',
                'descripcion_larga' => "Un imprescindible para amantes de la gastronomía vasca. El recorrido enlaza los bares más reconocidos de la Parte Vieja, donde los pinchos se exhiben en barra a la espera de los comensales. Locales como Borda Berri, La Cuchara de San Telmo o Ganbara figuran en cualquier lista del mejor tapeo del país.\n\nLa filosofía es ir de bar en bar tomando uno o dos pinchos en cada uno con un txikito de vino o un zurito de cerveza. La ruta se completa en una tarde, aunque conviene espaciarla y combinar con un paseo por la bahía de la Concha.",
                'categoria' => 'gastronomia',
                'dificultad' => 'facil',
                'distancia_km' => 1.5,
                'duracion_min' => 240,
                'lat_inicio' => 43.3253,
                'lng_inicio' => -1.9854,
                'punto_inicio' => 'Plaza de la Constitución',
                'punto_fin' => 'Mercado de la Bretxa',
                'mejor_epoca' => 'todo el año',
                'destacada' => true,
            ],
            [
                'titulo' => 'Ruta del Queso Manchego',
                'region_slug' => 'castilla-la-mancha',
                'descripcion' => 'Visitas a queserías artesanales con denominación de origen entre Quintanar y Manzanares.',
                'descripcion_larga' => "Recorrido por queserías de la denominación de origen Queso Manchego, donde aún se elabora con leche cruda de oveja manchega siguiendo métodos tradicionales. La ruta arranca en Quintanar de la Orden y atraviesa el Campo de San Juan, con paradas en Tomelloso, Alcázar de San Juan y Manzanares.\n\nLas queserías ofrecen visita guiada al obrador, cata comparada de quesos por curación y compra directa al productor. Se combina bien con un alto en algún molino de viento manchego o en una bodega local de Valdepeñas.",
                'categoria' => 'gastronomia',
                'dificultad' => 'facil',
                'distancia_km' => 95.0,
                'duracion_min' => 480,
                'lat_inicio' => 39.5912,
                'lng_inicio' => -3.0420,
                'punto_inicio' => 'Quintanar de la Orden',
                'punto_fin' => 'Manzanares',
                'mejor_epoca' => 'todo el año',
                'destacada' => false,
            ],
            [
                'titulo' => 'Ruta de la Sidra Asturiana',
                'region_slug' => 'asturias',
                'descripcion' => 'Llagares, espichas y manzanares por la comarca asturiana de la sidra entre Villaviciosa y Nava.',
                'descripcion_larga' => "Asturias produce el 80 % de la sidra natural de España y esta ruta recorre el corazón de la comarca, con visitas a llagares (bodegas de sidra), pomaradas y catas comentadas. Villaviciosa abre el camino con su histórica Casa Cortina y el Museo de la Sidra de Nava cierra el recorrido.\n\nEntre medias se cruzan pequeños pueblos asturianos donde se degustan platos tradicionales como los callos a la asturiana, el cachopo o la fabada acompañados de sidra escanciada. En primavera la floración del manzano transforma todo el paisaje en blanco y rosa.",
                'categoria' => 'gastronomia',
                'dificultad' => 'facil',
                'distancia_km' => 30.0,
                'duracion_min' => 360,
                'lat_inicio' => 43.4925,
                'lng_inicio' => -5.4361,
                'punto_inicio' => 'Villaviciosa',
                'punto_fin' => 'Nava',
                'mejor_epoca' => 'primavera y verano',
                'destacada' => false,
            ],
            [
                'titulo' => 'Ruta del Aceite de Cazorla',
                'region_slug' => 'andalucia',
                'descripcion' => 'Almazaras y olivares centenarios entre Cazorla, Quesada y Úbeda con catas de aceite de oliva virgen extra.',
                'descripcion_larga' => "La sierra de Cazorla alberga uno de los olivares más extensos del mundo y produce aceites con denominación de origen reconocidos internacionalmente. La ruta arranca en Cazorla, atraviesa Quesada y termina en la patrimonial Úbeda, con paradas en almazaras visitables.\n\nIncluye catas de aceite de oliva virgen extra de las variedades picual y royal, talleres de cocina con aceite y paseos entre olivares centenarios. Los meses de noviembre y diciembre son la temporada de la cosecha, con eventos y degustaciones especiales en los pueblos.",
                'categoria' => 'gastronomia',
                'dificultad' => 'facil',
                'distancia_km' => 75.0,
                'duracion_min' => 420,
                'lat_inicio' => 37.9114,
                'lng_inicio' => -3.0010,
                'punto_inicio' => 'Cazorla',
                'punto_fin' => 'Úbeda',
                'mejor_epoca' => 'noviembre y diciembre',
                'destacada' => false,
            ],
            [
                'titulo' => 'Ruta del Vino Ribera del Duero',
                'region_slug' => 'castilla-y-leon',
                'descripcion' => 'Bodegas centenarias y castillos riberenos entre Aranda de Duero, Peñafiel y Roa.',
                'descripcion_larga' => "La Ribera del Duero es una de las denominaciones de origen vinícolas más prestigiosas del país, con bodegas que van desde explotaciones familiares hasta proyectos de arquitectura espectacular firmados por Norman Foster o Richard Rogers. La ruta arranca en Aranda de Duero, capital comercial de la zona, atraviesa Peñafiel con su impresionante castillo-museo del vino y termina en Roa.\n\nIncluye visitas a bodegas, catas guiadas y paseos por viñedos antiguos junto al cauce del Duero. Combina especialmente bien con la gastronomía local, marcada por el lechazo asado y la morcilla de Burgos. La vendimia es la mejor época para vivir la ruta en plena actividad.",
                'categoria' => 'gastronomia',
                'dificultad' => 'facil',
                'distancia_km' => 60.0,
                'duracion_min' => 480,
                'lat_inicio' => 41.6705,
                'lng_inicio' => -3.6890,
                'punto_inicio' => 'Aranda de Duero',
                'punto_fin' => 'Roa',
                'mejor_epoca' => 'septiembre y octubre',
                'destacada' => true,
            ],
            [
                'titulo' => 'Las Médulas: sendero por la mina de oro romana',
                'region_slug' => 'castilla-y-leon',
                'descripcion' => 'Recorrido por la mayor mina de oro a cielo abierto del Imperio romano, hoy paisaje rojizo único.',
                'descripcion_larga' => "Las Médulas son el resultado de la mayor explotación aurífera del Imperio romano, donde Plinio el Viejo describió la técnica del 'ruina montium' que arrancaba montañas enteras con agua a presión. El paisaje resultante, declarado Patrimonio de la Humanidad, son acantilados rojizos coronados por castaños centenarios.\n\nLa ruta arranca en el pueblo de Las Médulas y sube hasta el mirador de Orellán, con vistas panorámicas sobre la antigua mina. El recorrido completo permite entrar en algunas galerías excavadas por los romanos. La luz del atardecer en otoño es especialmente espectacular.",
                'categoria' => 'patrimonio',
                'dificultad' => 'moderada',
                'distancia_km' => 8.0,
                'duracion_min' => 180,
                'lat_inicio' => 42.4716,
                'lng_inicio' => -6.7711,
                'punto_inicio' => 'Las Médulas',
                'punto_fin' => 'Mirador de Orellán',
                'mejor_epoca' => 'otoño',
                'destacada' => true,
            ],
            [
                'titulo' => 'Itálica: ciudad romana de Hispania',
                'region_slug' => 'andalucia',
                'descripcion' => 'Visita al anfiteatro y las ruinas de la primera ciudad romana fundada fuera de Italia, cuna de Trajano.',
                'descripcion_larga' => "Itálica fue la primera ciudad romana fundada fuera de la península itálica, en el año 206 a.C., y dio dos emperadores al imperio: Trajano y Adriano. El yacimiento conserva el tercer anfiteatro más grande del mundo romano, con capacidad para 25 000 espectadores, además de mosaicos espectaculares en domus aristocráticas.\n\nEl recorrido empieza en el centro de visitantes y atraviesa el cardo y decumano hasta el anfiteatro, escenario de localizaciones de Juego de Tronos. Conviene combinar la visita con Sevilla, a 9 kilómetros, y planificar la ida temprano en verano por el calor.",
                'categoria' => 'patrimonio',
                'dificultad' => 'facil',
                'distancia_km' => 4.0,
                'duracion_min' => 180,
                'lat_inicio' => 37.4378,
                'lng_inicio' => -6.0451,
                'punto_inicio' => 'Santiponce',
                'punto_fin' => 'Anfiteatro de Itálica',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => false,
            ],
            [
                'titulo' => 'Atapuerca: yacimiento prehistórico',
                'region_slug' => 'castilla-y-leon',
                'descripcion' => 'Visita guiada al yacimiento que ha redefinido la historia humana en Europa, Patrimonio de la Humanidad.',
                'descripcion_larga' => "Los yacimientos de la sierra de Atapuerca albergan los restos humanos más antiguos de Europa occidental, con más de 1,2 millones de años. Las cuevas de la Trinchera del Ferrocarril han revolucionado el conocimiento sobre la evolución humana en Eurasia y son Patrimonio de la Humanidad desde 2000.\n\nLa visita guiada arranca en el centro de visitantes de Ibeas de Juarros y sube a la sierra para conocer la Sima de los Huesos y la Gran Dolina. Conviene complementar con el Museo de la Evolución Humana en la propia Burgos. Solo se accede mediante visita guiada con reserva previa.",
                'categoria' => 'patrimonio',
                'dificultad' => 'moderada',
                'distancia_km' => 6.5,
                'duracion_min' => 240,
                'lat_inicio' => 42.3611,
                'lng_inicio' => -3.5253,
                'punto_inicio' => 'Ibeas de Juarros',
                'punto_fin' => 'Sima de los Huesos',
                'mejor_epoca' => 'primavera y otoño',
                'destacada' => false,
            ],
            [
                'titulo' => 'Mérida romana',
                'region_slug' => 'extremadura',
                'descripcion' => 'Recorrido por el conjunto monumental romano mejor conservado de la península, Patrimonio de la Humanidad.',
                'descripcion_larga' => "Mérida fue Augusta Emerita, capital de la provincia romana de Lusitania, fundada en el año 25 a.C. para los soldados veteranos de las guerras cántabras. Su conjunto monumental romano es el más completo de la península, con teatro, anfiteatro, circo, templos, casas y dos acueductos, todo declarado Patrimonio de la Humanidad.\n\nLa ruta enlaza el Teatro Romano (sede del Festival Internacional de Teatro Clásico cada verano), el Anfiteatro contiguo, la Casa del Mitreo con sus mosaicos y el Acueducto de los Milagros. Termina en el imprescindible Museo Nacional de Arte Romano firmado por Rafael Moneo.",
                'categoria' => 'patrimonio',
                'dificultad' => 'facil',
                'distancia_km' => 5.5,
                'duracion_min' => 240,
                'lat_inicio' => 38.9165,
                'lng_inicio' => -6.3434,
                'punto_inicio' => 'Teatro Romano',
                'punto_fin' => 'Acueducto de los Milagros',
                'mejor_epoca' => 'todo el año',
                'destacada' => true,
            ],
            [
                'titulo' => 'Altamira: la Capilla Sixtina del paleolítico',
                'region_slug' => 'cantabria',
                'descripcion' => 'Museo, neocueva y entorno de Altamira, joya del arte rupestre paleolítico declarada Patrimonio de la Humanidad.',
                'descripcion_larga' => "La cueva de Altamira contiene una de las muestras más sobresalientes de arte rupestre paleolítico del mundo, con bisontes pintados hace unos 14 000 años. La cueva original solo es accesible mediante sorteo a un máximo de cinco visitantes por semana, pero el Museo Nacional incluye una neocueva idéntica que reproduce la sala de los bisontes con todo lujo de detalle.\n\nLa visita combina el museo, la neocueva y el paseo por el entorno hasta Santillana del Mar, una de las villas medievales mejor conservadas de España. Es ideal para una jornada en familia, con alojamiento recomendado en Santillana o en la cercana Comillas.",
                'categoria' => 'patrimonio',
                'dificultad' => 'facil',
                'distancia_km' => 3.5,
                'duracion_min' => 240,
                'lat_inicio' => 43.3791,
                'lng_inicio' => -4.1182,
                'punto_inicio' => 'Santillana del Mar',
                'punto_fin' => 'Cuevas de Altamira',
                'mejor_epoca' => 'todo el año',
                'destacada' => false,
            ],
        ];
    }
}
